Descargar dataset

In [60]:
from PIL import Image
import os
import kagglehub
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from tqdm.auto import tqdm
import torch

In [ ]:
path = kagglehub.dataset_download("mrigaankjaswal/capcha-images-to-training-data", output_dir="./dataset")
print("Path to dataset files:", path)

Downloading to ./dataset/1.archive...

100%|██████████| 8.71M/8.71M [00:00<00:00, 11.5MB/s]

Extracting files...

Path to dataset files: ./dataset

Crear una ED que pueda contenerlos y guardarlos

In [13]:
class imagen():
    def __init__(self, path):
        self.dir = path
        self.target = path.split("/")[-1].split(".")[-2]
        self.image = Image.open(path)

imagenes = []

archivos = os.listdir("./dataset/samples")
imagenes = [imagen(f"./dataset/samples/{archivo}") for archivo in archivos  if archivo.endswith("png")]

In [80]:
class CaptchaDataset(Dataset):
    def __init__(self, directory, files, transform=None, device="cuda"):
        self.directory = directory
        self.transform = transform
        self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

        self.files = [
            file for file in files
            if file.endswith(".png")
        ]

        self.image = []
        
        for file in self.files:
            filename = file
            path = os.path.join(self.directory, filename)
            imagen = Image.open(path).convert("RGB")
            imagen = self.transform(imagen)
            imagen = imagen.to(self.device)
            self.image.append(imagen)

        target_not_normalizated = [ file.split(".")[-2] for file in self.files]

        chars = sorted(set("".join(target_not_normalizated)))
        self.char_to_idx = {char: i for i, char in enumerate(chars)}
        self.idx_to_char = {i: char for char, i in self.char_to_idx.items()}


        self.target = torch.tensor([
            [
                self.char_to_idx[caracter]
                for caracter in target_normalizated
            ] 
            for target_normalizated in target_not_normalizated
            ])
    def __len__(self):
        return len(self.files)

    def __getitem__(self, index):
        return self.image[index], self.target[index]

In [81]:
from sklearn.model_selection import train_test_split
files = [
    f
    for f in os.listdir("./dataset/samples")
    if f.endswith(".png")
]

train_files, test_files = train_test_split(
    files,
    test_size=0.2,
    random_state=42
)
transform = transforms.Compose([
    transforms.ToTensor()
])

train_dataset = CaptchaDataset(
    "./dataset/samples",
    train_files,
    transform=transform
)

test_dataset = CaptchaDataset(
    "./dataset/samples",
    test_files,
    transform=transform
)
train_dataloader = DataLoader(train_dataset, batch_size=64, shuffle=True)
test_dataloader = DataLoader(test_dataset, batch_size=64, shuffle=True)

In [77]:
import torch
import torch.nn as nn


class CaptchaCNN(nn.Module):
    def __init__(self, num_classes, captcha_length):
        super().__init__()

        self.features = nn.Sequential(
            nn.Conv2d(3, 32, 3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2),

            nn.Conv2d(32, 64, 3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2)
        )

        self.classifier = nn.Sequential(
            nn.Flatten(),
            nn.LazyLinear(128),
            nn.ReLU(),
            nn.Linear(128, captcha_length * num_classes)
        )

        self.num_classes = num_classes
        self.captcha_length = captcha_length

    def forward(self, x):
        x = self.features(x)
        x = self.classifier(x)
        x = x.view(-1, self.captcha_length, self.num_classes)

        return x

In [99]:
num_classes = len(train_dataset.char_to_idx)
captcha_length = train_dataset.target.shape[1]

print(num_classes)
print(captcha_length)

19
5

In [100]:
class Early_Stop():
  def __init__(self, patience=5, delta=0):
    self.patience = patience
    self.delta = delta
    self.best_val_loss = None
    self.no_val_improvement_times = 0
    self.stop = False

  def check_stop(self, val_loss):
    if self.best_val_loss is None or (val_loss + self.delta) < self.best_val_loss:
      self.best_val_loss = val_loss
      self.no_val_improvement_times = 0
    else:
      self.no_val_improvement_times += 1
      self.stop = self.no_val_improvement_times >= self.patience



from tqdm.auto import tqdm
import torch


def learning_loop(
    train_dataloader,
    model,
    epochs,
    loss_fn,
    learning_rate,
    optimizer,
    device = "cuda"
):
    epoch_loss_list = []
    epoch_char_acc_list = []
    epoch_captcha_acc_list = []

    opt = optimizer(
        model.parameters(),
        lr=learning_rate
    )

    with tqdm(range(epochs), desc="Training") as pbar:

        for epoch in pbar:

            model.train()

            total_loss = 0.0
            total_chars = 0
            correct_chars = 0

            total_captchas = 0
            correct_captchas = 0

            for x_true, y_true in train_dataloader:

                x_true = x_true.to(device)
                y_true = y_true.to(device)

                # Forward
                y_pred = model(x_true)

                # Loss
                loss = loss_fn(
                    y_pred.reshape(-1, num_classes),
                    y_true.reshape(-1)
                )

                # Backward
                opt.zero_grad()
                loss.backward()
                opt.step()

                total_loss += loss.item()

                # Predicción
                predictions = torch.argmax(
                    y_pred,
                    dim=-1
                )

                # Accuracy por carácter
                correct_chars += (
                    predictions == y_true
                ).sum().item()

                total_chars += y_true.numel()

                # Accuracy por CAPTCHA completo
                captcha_correct = (
                    predictions == y_true
                ).all(dim=1)

                correct_captchas += captcha_correct.sum().item()
                total_captchas += y_true.size(0)

            # Métricas de la época
            epoch_loss = total_loss / len(train_dataloader)

            char_accuracy = (
                correct_chars / total_chars
            )

            captcha_accuracy = (
                correct_captchas / total_captchas
            )

            epoch_loss_list.append(epoch_loss)
            epoch_char_acc_list.append(char_accuracy)
            epoch_captcha_acc_list.append(captcha_accuracy)

            pbar.set_postfix({
                "loss": f"{epoch_loss:.4f}",
                "char_acc": f"{char_accuracy:.2%}",
                "captcha_acc": f"{captcha_accuracy:.2%}"
            })

    return (
        model,
        epoch_loss_list,
        epoch_char_acc_list,
        epoch_captcha_acc_list
    )

In [111]:
device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

model = CaptchaCNN(
    num_classes=num_classes,
    captcha_length=captcha_length
).to(device)

criterion = nn.CrossEntropyLoss()

optimizer = torch.optim.Adam(
    model.parameters(),
    lr=0.001
)
model, loss_history, char_acc_history, captcha_acc_history = learning_loop(
    train_dataloader=train_dataloader,
    model=model,
    epochs=40,
    loss_fn=criterion,
    learning_rate=0.001,
    optimizer=torch.optim.Adam
)

Training: 100%|██████████| 40/40 [00:14<00:00,  2.84it/s, loss=0.0004, char_acc=100.00%, captcha_acc=100.00%]

In [114]:
import pandas as pd
import torch

def predict_dataset(model, dataset, device):
    model.eval()

    results = []

    with torch.no_grad():

        for i in range(len(dataset)):

            image, target = dataset[i]

            image = image.unsqueeze(0).to(device)

            output = model(image)

            prediction = torch.argmax(output, dim=-1).squeeze(0)

            real = "".join(
                dataset.idx_to_char[idx.item()]
                for idx in target
            )

            predicted = "".join(
                dataset.idx_to_char[idx.item()]
                for idx in prediction
            )

            chars_correct = sum(
                a == b
                for a, b in zip(real, predicted)
            )

            results.append({
                "index": i,
                "file": dataset.files[i],
                "real": real,
                "prediction": predicted,
                "correct": real == predicted,
                "char_accuracy": chars_correct / len(real)
            })

    # DataFrame completo
    df = pd.DataFrame(results)

    # DataFrame resumen
    df_resume = pd.DataFrame({
        "samples": [len(df)],
        "captcha_accuracy": [df["correct"].mean()],
        "char_accuracy": [df["char_accuracy"].mean()],
        "captcha_correct": [df["correct"].sum()],
        "captcha_incorrect": [(~df["correct"]).sum()]
    })

    return df, df_resume

df, df_resume = predict_dataset(
    model,
    test_dataset,
    device
)

display(df_resume)
display(df)

,samples,captcha_accuracy,char_accuracy,captcha_correct,captcha_incorrect
0,208,0.134615,0.654808,28,180

     index       file   real prediction  correct  char_accuracy
0        0  4fc36.png  4fc36      4fc36     True            1.0
1        1  fyfbn.png  fyfbn      fdfxn    False            0.6
2        2  5mgn4.png  5mgn4      5ngnf    False            0.6
3        3  2mg87.png  2mg87      7pg27    False            0.4
4        4  gw53m.png  gw53m      gw75m    False            0.6
5        5  x2cnn.png  x2cnn      x3cnn    False            0.8
6        6  7bwm2.png  7bwm2      7bwn8    False            0.6
7        7  8684m.png  8684m      5464m    False            0.4
8        8  d66cn.png  d66cn      d4ncn    False            0.6
9        9  bd3b7.png  bd3b7      bd5b7    False            0.8
10      10  gnbde.png  gnbde      gnbdb    False            0.8
11      11  e667x.png  e667x      26f7x    False            0.6
12      12  pgm2e.png  pgm2e      pgm7m    False            0.6
13      13  n5w5g.png  n5w5g      p5w5g    False            0.8
14      14  6n5fd.png  6n5fd      en5fd    False            0.8
15      15  3den6.png  3den6      3cen6    False            0.8
16      16  n8fp6.png  n8fp6      n6fe6    False            0.6
17      17  p6mn8.png  p6mn8      p6my8    False            0.8
18      18  88y52.png  88y52      y8822    False            0.4
19      19  fywb8.png  fywb8      wwwn8    False            0.4
20      20  xe6eb.png  xe6eb      x45eb    False            0.6
21      21  ngn26.png  ngn26      ncn23    False            0.6
22      22  b35f6.png  b35f6      b25f8    False            0.6
23      23  mggce.png  mggce      mxyfe    False            0.4
24      24  fp762.png  fp762      fp782    False            0.8
25      25  c3n8x.png  c3n8x      c3m4c    False            0.4
26      26  wce5n.png  wce5n      wwm5m    False            0.4
27      27  3n7mx.png  3n7mx      363nn    False            0.2
28      28  7y2x4.png  7y2x4      7y2n4    False            0.8
29      29  f4wfn.png  f4wfn      b3xfn    False            0.4
30      30  5dxnm.png  5dxnm      5dwnn    False            0.6
31      31  63824.png  63824      63d84    False            0.6
32      32  dmw8n.png  dmw8n      dmnnm    False            0.4
33      33  xemyg.png  xemyg      xe4yp    False            0.6
34      34  x74b2.png  x74b2      x74b2     True            1.0
35      35  445cc.png  445cc      445e2    False            0.6
36      36  c6f8g.png  c6f8g      c6dmp    False            0.4
37      37  e8e5e.png  e8e5e      e3e5e    False            0.8
38      38  e3ndn.png  e3ndn      65ndn    False            0.6
39      39  36bc2.png  36bc2      36bc2     True            1.0
40      40  e72cd.png  e72cd      e72c5    False            0.8
41      41  m457d.png  m457d      m467b    False            0.6
42      42  m2nf4.png  m2nf4      mfbf4    False            0.6
43      43  5pm6b.png  5pm6b      5wmm6    False            0.4
44      44  nbcgb.png  nbcgb      nbcpb    False            0.8
45      45  mpxfb.png  mpxfb      mpx7b    False            0.8
46      46  c7gb3.png  c7gb3      c7n63    False            0.6
47      47  defyx.png  defyx      defyb    False            0.8
48      48  x4pnp.png  x4pnp      x4pnp     True            1.0
49      49  76nxn.png  76nxn      76nxn     True            1.0
50      50  82fx2.png  82fx2      d2fx7    False            0.6
51      51  32dnn.png  32dnn      32dnn     True            1.0
52      52  pwmbn.png  pwmbn      py6dm    False            0.2
53      53  43mn5.png  43mn5      wmmm5    False            0.4
54      54  xngxc.png  xngxc      efg6e    False            0.2
55      55  yd3m3.png  yd3m3      yd3n4    False            0.6
56      56  y5n6d.png  y5n6d      y3m63    False            0.4
57      57  xbem6.png  xbem6      xbemd    False            0.8
58      58  25257.png  25257      2525f    False            0.8
59      59  dbny3.png  dbny3      dbny3     True            1.0
60      60  dn2ym.png  dn2ym      dd2yb    False            0.6
61      61  gm2c2.png  gm2c2      gdec2    False            0.6
62      62  3bd8f.png  3bd8f      3bd8f     True            1.0
63      63  yyn57.png  yyn57      yym57    False            0.8
64      64  fxpw3.png  fxpw3      7npw2    False            0.4
65      65  6p7gx.png  6p7gx      6p7gx     True            1.0
66      66  8nn73.png  8nn73      8nn73     True            1.0
67      67  be6np.png  be6np      ne6np    False            0.8
68      68  8db67.png  8db67      8db87    False            0.8
69      69  c55c6.png  c55c6      c5565    False            0.6
70      70  dw6mn.png  dw6mn      dm6nm    False            0.4
71      71  8b735.png  8b735      86337    False            0.4
72      72  4gycb.png  4gycb      4gmcb    False            0.8
73      73  pp546.png  pp546      pp748    False            0.6
74      74  n5cm7.png  n5cm7      n7cn7    False            0.6
75      75  7w67m.png  7w67m      wm67n    False            0.4
76      76  wgnwp.png  wgnwp      wymnm    False            0.2
77      77  4n2yg.png  4n2yg      dm2yg    False            0.6
78      78  yx2d4.png  yx2d4      yx8d4    False            0.8
79      79  yeyn4.png  yeyn4      yeyn4     True            1.0
80      80  men4f.png  men4f      nfg4f    False            0.4
81      81  x5f54.png  x5f54      x7f5w    False            0.6
82      82  3nfdn.png  3nfdn      3nfxn    False            0.8
83      83  p2m6n.png  p2m6n      p2n66    False            0.6
84      84  7gp47.png  7gp47      7gm47    False            0.8
85      85  3ye2e.png  3ye2e      3yd3e    False            0.6
86      86  7pcd7.png  7pcd7      7pc87    False            0.8
87      87  pdcp4.png  pdcp4      mdcn4    False            0.6
88      88  cd4eg.png  cd4eg      nn4eb    False            0.4
89      89  3wnd3.png  3wnd3      5nnd3    False            0.6
90      90  nmw46.png  nmw46      nn848    False            0.4
91      91  ndg2b.png  ndg2b      ndg2n    False            0.8
92      92  2gyb6.png  2gyb6      2gyb8    False            0.8
93      93  55y2m.png  55y2m      65w2m    False            0.6
94      94  m2576.png  m2576      mx55f    False            0.4
95      95  33p4e.png  33p4e      33p4e     True            1.0
96      96  2cg58.png  2cg58      2cg58     True            1.0
97      97  ffd6p.png  ffd6p      fn5e6    False            0.2
98      98  mxnw4.png  mxnw4      mmfmw    False            0.2
99      99  gbxyy.png  gbxyy      gb4xy    False            0.6
100    100  g3dy6.png  g3dy6      n2fy6    False            0.4
101    101  f85y3.png  f85y3      f25p8    False            0.4
102    102  5fyem.png  5fyem      5f4dn    False            0.4
103    103  23mdg.png  23mdg      25ndg    False            0.6
104    104  7634y.png  7634y      7636y    False            0.8
105    105  f6ne5.png  f6ne5      f6ne6    False            0.8
106    106  7d44m.png  7d44m      x344m    False            0.6
107    107  7f8b3.png  7f8b3      7f8b3     True            1.0
108    108  nn4wx.png  nn4wx      nnwww    False            0.6
109    109  pm47f.png  pm47f      mp57f    False            0.4
110    110  6bxwg.png  6bxwg      6bgng    False            0.6
111    111  646x8.png  646x8      646w8    False            0.8
112    112  cewnm.png  cewnm      dewnm    False            0.8
113    113  wg625.png  wg625      wy825    False            0.6
114    114  wxy4n.png  wxy4n      wnp4b    False            0.4
115    115  yemy4.png  yemy4      ywwnw    False            0.2
116    116  bmxpe.png  bmxpe      ne6pp    False            0.2
117    117  377xx.png  377xx      373xn    False            0.6
118    118  7yf62.png  7yf62      7y738    False            0.4
119    119  cnex4.png  cnex4      en8n4    False            0.4
120    120  c6we6.png  c6we6      c6xx6    False            0.6
121    121  3xng6.png  3xng6      3xng6     True            1.0
122    122  8c2wy.png  8c2wy      6c2wm    False            0.6
123    123  ccn2x.png  ccn2x      ecn2y    False            0.6
124    124  bnc5f.png  bnc5f      bnc5c    False            0.8
125    125  42xpy.png  42xpy      42xpw    False            0.8
126    126  58b5m.png  58b5m      56n6m    False            0.4
127    127  2pfpn.png  2pfpn      2nfnn    False            0.6
128    128  5p8fm.png  5p8fm      5pd6n    False            0.4
129    129  6dmx7.png  6dmx7      edpw7    False            0.4
130    130  ennmm.png  ennmm      ewwwm    False            0.4
131    131  5nm6d.png  5nm6d      5n66d    False            0.8
132    132  m8m4x.png  m8m4x      m3m6x    False            0.6
133    133  mgw3n.png  mgw3n      pgg3n    False            0.6
134    134  37ep6.png  37ep6      37bp6    False            0.8
135    135  387g2.png  387g2      387g2     True            1.0
136    136  wecfd.png  wecfd      wccfd    False            0.8
137    137  d8dce.png  d8dce      d8cce    False            0.8
138    138  658xe.png  658xe      65pxe    False            0.8
139    139  nxc83.png  nxc83      nnc86    False            0.6
140    140  nxxf8.png  nxxf8      nxxf8     True            1.0
141    141  gcx6f.png  gcx6f      gcxxf    False            0.8
142    142  8gmnx.png  8gmnx      8gmnm    False            0.8
143    143  pdyc8.png  pdyc8      mdycn    False            0.6
144    144  f8f8g.png  f8f8g      f8d8g    False            0.8
145    145  edg3p.png  edg3p      ndg3c    False            0.6
146    146  pmg55.png  pmg55      pmg5f    False            0.8
147    147  ncw4g.png  ncw4g      ncg4g    False            0.8
148    148  ycnfc.png  ycnfc      b3nfn    False            0.4
149    149  n265y.png  n265y      n265w    False            0.8
150    150  7nnnx.png  7nnnx      7nnnx     True            1.0
151    151  mbf58.png  mbf58      m3858    False            0.6
152    152  bm3p8.png  bm3p8      ew3p8    False            0.6
153    153  2356g.png  2356g      2355g    False            0.8
154    154  c43b4.png  c43b4      c43n4    False            0.8
155    155  e5n66.png  e5n66      e3n86    False            0.6
156    156  n7ff2.png  n7ff2      n7ff2     True            1.0
157    157  8eggg.png  8eggg      8eggg     True            1.0
158    158  xnfx5.png  xnfx5      xffx5    False            0.8
159    159  xxbm5.png  xxbm5      xxxn5    False            0.6
160    160  nbwpn.png  nbwpn      nbwpm    False            0.8
161    161  d2ycw.png  d2ycw      d2xxn    False            0.4
162    162  wc2bd.png  wc2bd      dc2bd    False            0.8
163    163  8n62n.png  8n62n      8n62n     True            1.0
164    164  ecd4w.png  ecd4w      cc34w    False            0.6
165    165  f2fge.png  f2fge      f25gx    False            0.6
166    166  mgdwb.png  mgdwb      mgdmf    False            0.6
167    167  xcf88.png  xcf88      xff86    False            0.6
168    168  pnnwy.png  pnnwy      4nnnw    False            0.4
169    169  664nf.png  664nf      563nf    False            0.6
170    170  8nbew.png  8nbew      8nbew     True            1.0
171    171  n3x4c.png  n3x4c      n3x4c     True            1.0
172    172  e6m6p.png  e6m6p      c6n6w    False            0.4
173    173  6fn84.png  6fn84      6fn83    False            0.8
174    174  n7dyb.png  n7dyb      n73yb    False            0.8
175    175  w4cdc.png  w4cdc      w4cdb    False            0.8
176    176  7m8px.png  7m8px      7x8nx    False            0.6
177    177  42nxy.png  42nxy      47exy    False            0.6
178    178  xxney.png  xxney      xxndp    False            0.6
179    179  34b84.png  34b84      33b84    False            0.8
180    180  4743p.png  4743p      4743p     True            1.0
181    181  nf8b8.png  nf8b8      nf8b8     True            1.0
182    182  2en7g.png  2en7g      2en7x    False            0.8
183    183  3bnyf.png  3bnyf      3bmpf    False            0.6
184    184  63pxe.png  63pxe      63pme    False            0.8
185    185  2xc2n.png  2xc2n      2xc2n     True            1.0
186    186  7wnpm.png  7wnpm      7m6pm    False            0.6
187    187  pg2yx.png  pg2yx      pg7ym    False            0.6
188    188  gecmf.png  gecmf      gecnf    False            0.8
189    189  87d4c.png  87d4c      37d6n    False            0.4
190    190  wm47f.png  wm47f      wmm67    False            0.4
191    191  8n2pg.png  8n2pg      6n2pg    False            0.8
192    192  x7746.png  x7746      x7745    False            0.8
193    193  g55b4.png  g55b4      g33b4    False            0.6
194    194  mddgb.png  mddgb      mddgn    False            0.8
195    195  8y63f.png  8y63f      8y52c    False            0.4
196    196  gymmn.png  gymmn      gy8np    False            0.4
197    197  ng756.png  ng756      np75m    False            0.6
198    198  e2mg2.png  e2mg2      c2mn2    False            0.6
199    199  fg38b.png  fg38b      4g28m    False            0.4
200    200  cfw6e.png  cfw6e      cfg6e    False            0.8
201    201  y48c3.png  y48c3      y78b3    False            0.6
202    202  8np22.png  8np22      8np22     True            1.0
203    203  e4gd7.png  e4gd7      y4gc2    False            0.4
204    204  fnbfw.png  fnbfw      wnwfx    False            0.4
205    205  36nx4.png  36nx4      36nx4     True            1.0
206    206  p2dw7.png  p2dw7      p2dn7    False            0.8
207    207  y866y.png  y866y      yf86y    False            0.6

In [76]:
pd.set_option("display.max_rows", None)
df

      index       file   real prediction  correct  char_accuracy
0         0  226md.png  226md      22xnd    False            0.6
1         1  22d5n.png  22d5n      27d5n    False            0.8
2         2  2356g.png  2356g      2n66n    False            0.4
3         3  23mdg.png  23mdg      33mdg    False            0.8
4         4  23n88.png  23n88      23n88     True            1.0
5         5  243mm.png  243mm      f43mm    False            0.8
6         6  244e2.png  244e2      244e2     True            1.0
7         7  245y5.png  245y5      645y5    False            0.8
8         8  24f6w.png  24f6w      24f6w     True            1.0
9         9  24pew.png  24pew      24pew     True            1.0
10       10  25257.png  25257      f5257    False            0.8
11       11  253dc.png  253dc      nf3d8    False            0.4
12       12  25egp.png  25egp      2fegp    False            0.8
13       13  25m6p.png  25m6p      25m6p     True            1.0
14       14  25p2m.png  25p2m      25p2m     True            1.0
15       15  25w53.png  25w53      25w53     True            1.0
16       16  264m5.png  264m5      f64w5    False            0.6
17       17  268g2.png  268g2      268g2     True            1.0
18       18  28348.png  28348      28348     True            1.0
19       19  28x47.png  28x47      28x47     True            1.0
20       20  2b827.png  2b827      2b827     True            1.0
21       21  2bg48.png  2bg48      2bg48     True            1.0
22       22  2cegf.png  2cegf      2ceg8    False            0.8
23       23  2cg58.png  2cg58      2cg48    False            0.8
24       24  2cgyx.png  2cgyx      2cgyx     True            1.0
25       25  2en7g.png  2en7g      2en7g     True            1.0
26       26  2enf4.png  2enf4      2enf4     True            1.0
27       27  2fxgd.png  2fxgd      2fxgd     True            1.0
28       28  2g783.png  2g783      2g783     True            1.0
29       29  2g7nm.png  2g7nm      2w7nm    False            0.8
30       30  2gyb6.png  2gyb6      2gyb6     True            1.0
31       31  2mg87.png  2mg87      2mg87     True            1.0
32       32  2mpnn.png  2mpnn      2mpnn     True            1.0
33       33  2n73f.png  2n73f      2n73f     True            1.0
34       34  2nbcx.png  2nbcx      2nxcx    False            0.8
35       35  2nf26.png  2nf26      2nf26     True            1.0
36       36  2npg6.png  2npg6      2npg6     True            1.0
37       37  2nx38.png  2nx38      2nx38     True            1.0
38       38  2p2y8.png  2p2y8      2cxy8    False            0.6
39       39  2pfpn.png  2pfpn      2nfpn    False            0.8
40       40  2w4y7.png  2w4y7      2w4y7     True            1.0
41       41  2wc38.png  2wc38      2wc38     True            1.0
42       42  2wx73.png  2wx73      2wx73     True            1.0
43       43  2x7bm.png  2x7bm      2x7bm     True            1.0
44       44  2xc2n.png  2xc2n      2xc2n     True            1.0
45       45  2ycn8.png  2ycn8      2ycn8     True            1.0
46       46  2yggg.png  2yggg      2yggg     True            1.0
47       47  325fb.png  325fb      375fb    False            0.8
48       48  32cnn.png  32cnn      32cnn     True            1.0
49       49  32dnn.png  32dnn      32dnn     True            1.0
50       50  33b22.png  33b22      33f22    False            0.8
51       51  33f7m.png  33f7m      33f8m    False            0.8
52       52  33n73.png  33n73      33n73     True            1.0
53       53  33ng4.png  33ng4      33ng8    False            0.8
54       54  33p4e.png  33p4e      33p4e     True            1.0
55       55  34b84.png  34b84      34b84     True            1.0
56       56  34fxm.png  34fxm      34fxm     True            1.0
57       57  34pcn.png  34pcn      34pcn     True            1.0
58       58  368y5.png  368y5      368w5    False            0.8
59       59  36bc2.png  36bc2      f6bc2    False            0.8
60       60  36nx4.png  36nx4      36nx4     True            1.0
61       61  36w25.png  36w25      36w85    False            0.8
62       62  373gb.png  373gb      373gb     True            1.0
63       63  377xx.png  377xx      377xx     True            1.0
64       64  378e5.png  378e5      378e5     True            1.0
65       65  37d52.png  37d52      37d52     True            1.0
66       66  37ep6.png  37ep6      37ep8    False            0.8
67       67  387g2.png  387g2      38fg2    False            0.8
68       68  38n57.png  38n57      38n57     True            1.0
69       69  3b4we.png  3b4we      3b4we     True            1.0
70       70  3bd8f.png  3bd8f      3bd8f     True            1.0
71       71  3bfnd.png  3bfnd      3bfnd     True            1.0
72       72  3bnyf.png  3bnyf      5bnyf    False            0.8
73       73  3bx86.png  3bx86      3bx86     True            1.0
74       74  3cpwb.png  3cpwb      3cpwb     True            1.0
75       75  3d7bd.png  3d7bd      3d7bd     True            1.0
76       76  3den6.png  3den6      3nen8    False            0.6
77       77  3dgmf.png  3dgmf      3dgmf     True            1.0
78       78  3ebnn.png  3ebnn      3ebnn     True            1.0
79       79  3ebpw.png  3ebpw      3ebpw     True            1.0
80       80  3eny7.png  3eny7      3nny7    False            0.8
81       81  3fbxd.png  3fbxd      3fbxd     True            1.0
82       82  3g2w6.png  3g2w6      3g2w6     True            1.0
83       83  3mxdn.png  3mxdn      3mxdn     True            1.0
84       84  3n2b4.png  3n2b4      3n284    False            0.8
85       85  3n3cf.png  3n3cf      5n3cf    False            0.8
86       86  3n7mx.png  3n7mx      3n7mx     True            1.0
87       87  3ndxd.png  3ndxd      3ndxd     True            1.0
88       88  3nfdn.png  3nfdn      3nfdn     True            1.0
89       89  3nnpw.png  3nnpw      3nnpw     True            1.0
90       90  3nw7w.png  3nw7w      3nw7w     True            1.0
91       91  3ny45.png  3ny45      3ny45     True            1.0
92       92  3p4nn.png  3p4nn      3p4nn     True            1.0
93       93  3p67n.png  3p67n      3p67n     True            1.0
94       94  3pe4g.png  3pe4g      3pe4g     True            1.0
95       95  3w2bw.png  3w2bw      3w2bw     True            1.0
96       96  3wnd3.png  3wnd3      3wnd3     True            1.0
97       97  3x325.png  3x325      3x325     True            1.0
98       98  3x5fm.png  3x5fm      3x5fm     True            1.0
99       99  3xcgg.png  3xcgg      3xcgg     True            1.0
100     100  3xng6.png  3xng6      3xng6     True            1.0
101     101  3ye2e.png  3ye2e      3ye2e     True            1.0
102     102  3ygde.png  3ygde      3ygdc    False            0.8
103     103  3ym7f.png  3ym7f      3ym7f     True            1.0
104     104  428b6.png  428b6      428b6     True            1.0
105     105  42dw4.png  42dw4      w2dw4    False            0.8
106     106  42nxy.png  42nxy      22nxy    False            0.8
107     107  42xpy.png  42xpy      42xpy     True            1.0
108     108  43gey.png  43gey      43gey     True            1.0
109     109  43mn5.png  43mn5      43gn5    False            0.8
110     110  43p5d.png  43p5d      43p5d     True            1.0
111     111  43xfe.png  43xfe      n3x4c    False            0.4
112     112  4433m.png  4433m      4433m     True            1.0
113     113  445cc.png  445cc      445ec    False            0.8
114     114  44c22.png  44c22      44c22     True            1.0
115     115  44fyb.png  44fyb      44fyb     True            1.0
116     116  44xe8.png  44xe8      44xe8     True            1.0
117     117  44ype.png  44ype      44ype     True            1.0
118     118  467d5.png  467d5      467d5     True            1.0
119     119  46mbm.png  46mbm      46mbm     True            1.0
120     120  4743p.png  4743p      4743p     True            1.0
121     121  474ff.png  474ff      474ff     True            1.0
122     122  478nx.png  478nx      478nx     True            1.0
123     123  47e4p.png  47e4p      47e4p     True            1.0
124     124  47m2b.png  47m2b      47m2b     True            1.0
125     125  488de.png  488de      488de     True            1.0
126     126  4b2pw.png  4b2pw      4b2pw     True            1.0
127     127  4c8n8.png  4c8n8      4c8n8     True            1.0
128     128  4cfw8.png  4cfw8      4cfw8     True            1.0
129     129  4cn7b.png  4cn7b      4cn7b     True            1.0
130     130  4d22m.png  4d22m      4d22m     True            1.0
131     131  4dgf7.png  4dgf7      4dgf7     True            1.0
132     132  4dw3w.png  4dw3w      wn63m    False            0.2
133     133  4egem.png  4egem      4egem     True            1.0
134     134  4exnn.png  4exnn      4exnn     True            1.0
135     135  4f8yp.png  4f8yp      478yp    False            0.8
136     136  4fc36.png  4fc36      4fc36     True            1.0
137     137  4fp5g.png  4fp5g      4fp5g     True            1.0
138     138  4gb3f.png  4gb3f      4g53f    False            0.8
139     139  4gycb.png  4gycb      ngycb    False            0.8
140     140  4m2w5.png  4m2w5      4m2w5     True            1.0
141     141  4n2yg.png  4n2yg      4n2yg     True            1.0
142     142  4n3mn.png  4n3mn      wn3mn    False            0.8
143     143  4nc37.png  4nc37      4nc37     True            1.0
144     144  4nnf3.png  4nnf3      4nnf3     True            1.0
145     145  4w6mw.png  4w6mw      4w6mw     True            1.0
146     146  4w76g.png  4w76g      4w76g     True            1.0
147     147  4yc85.png  4yc85      4yc85     True            1.0
148     148  4ycex.png  4ycex      4ycec    False            0.8
149     149  4ynf3.png  4ynf3      4ynf3     True            1.0
150     150  52447.png  52447      52447     True            1.0
151     151  5325m.png  5325m      5325m     True            1.0
152     152  537nf.png  537nf      537nf     True            1.0
153     153  53mn8.png  53mn8      53mn8     True            1.0
154     154  53wb8.png  53wb8      53wn8    False            0.8
155     155  53wp3.png  53wp3      53wp8    False            0.8
156     156  556wd.png  556wd      555wd    False            0.8
157     157  55w5c.png  55w5c      55y5c    False            0.8
158     158  55y2m.png  55y2m      55y2m     True            1.0
159     159  56c34.png  56c34      53c34    False            0.8
160     160  56m6y.png  56m6y      56m6y     True            1.0
161     161  56ncx.png  56ncx      56ncx     True            1.0
162     162  573bn.png  573bn      573bn     True            1.0
163     163  573d8.png  573d8      573d8     True            1.0
164     164  574d7.png  574d7      574d7     True            1.0
165     165  57b27.png  57b27      57b27     True            1.0
166     166  57gnx.png  57gnx      57gnc    False            0.8
167     167  57wdp.png  57wdp      57wnp    False            0.8
168     168  58b5m.png  58b5m      58b5x    False            0.8
169     169  58pnp.png  58pnp      58pnp     True            1.0
170     170  5bb66.png  5bb66      5bb66     True            1.0
171     171  5bg8f.png  5bg8f      5bg8f     True            1.0
172     172  5bgp2.png  5bgp2      5bgp2     True            1.0
173     173  5bnd7.png  5bnd7      5bnd7     True            1.0
174     174  5dxnm.png  5dxnm      5nxnm    False            0.8
175     175  5ep3n.png  5ep3n      5ep3n     True            1.0
176     176  5expp.png  5expp      5expp     True            1.0
177     177  5f3gf.png  5f3gf      573gf    False            0.8
178     178  5fyem.png  5fyem      5fyem     True            1.0
179     179  5g5e5.png  5g5e5      5g5e5     True            1.0
180     180  5gcd3.png  5gcd3      5gcd3     True            1.0
181     181  5mcy7.png  5mcy7      5mcy7     True            1.0
182     182  5mf7c.png  5mf7c      5mf7c     True            1.0
183     183  5mfff.png  5mfff      5mfff     True            1.0
184     184  5mgn4.png  5mgn4      5ngn4    False            0.8
185     185  5mnpd.png  5mnpd      5mnpd     True            1.0
186     186  5n245.png  5n245      5n245     True            1.0
187     187  5n3w4.png  5n3w4      5n3w8    False            0.8
188     188  5n728.png  5n728      5n728     True            1.0
189     189  5n732.png  5n732      5n732     True            1.0
190     190  5ng6e.png  5ng6e      5ng6e     True            1.0
191     191  5nggg.png  5nggg      5nggg     True            1.0
192     192  5nm6d.png  5nm6d      5nw6d    False            0.8
193     193  5nnff.png  5nnff      5nnff     True            1.0
194     194  5np4m.png  5np4m      5np4m     True            1.0
195     195  5npdn.png  5npdn      5npdn     True            1.0
196     196  5nxnn.png  5nxnn      5nxnn     True            1.0
197     197  5p3mm.png  5p3mm      5p3mm     True            1.0
198     198  5p8fm.png  5p8fm      5p8fm     True            1.0
199     199  5pm6b.png  5pm6b      5pw6b    False            0.8
200     200  5wddw.png  5wddw      5wdnw    False            0.8
201     201  5x5nx.png  5x5nx      5x5nx     True            1.0
202     202  5x7x5.png  5x7x5      5x7x5     True            1.0
203     203  5xd2e.png  5xd2e      5xd2e     True            1.0
204     204  5xwcg.png  5xwcg      dxwcn    False            0.6
205     205  5ywwf.png  5ywwf      5ywwf     True            1.0
206     206  5yxgp.png  5yxgp      5yxgp     True            1.0
207     207  62nb3.png  62nb3      62nb3     True            1.0
208     208  63824.png  63824      63824     True            1.0
209     209  63pxe.png  63pxe      63pxe     True            1.0
210     210  646x8.png  646x8      645x8    False            0.8
211     211  64b3p.png  64b3p      64e3p    False            0.8
212     212  64m82.png  64m82      64p82    False            0.8
213     213  658xe.png  658xe      638xe    False            0.8
214     214  65ebm.png  65ebm      6eebm    False            0.8
215     215  65m85.png  65m85      65m85     True            1.0
216     216  662bw.png  662bw      662bw     True            1.0
217     217  664dn.png  664dn      664dn     True            1.0
218     218  664nf.png  664nf      684n8    False            0.6
219     219  66wp5.png  66wp5      66wp5     True            1.0
220     220  675p3.png  675p3      675p3     True            1.0
221     221  677g3.png  677g3      677g3     True            1.0
222     222  678w3.png  678w3      678w3     True            1.0
223     223  67dey.png  67dey      67dex    False            0.8
224     224  6825y.png  6825y      6825y     True            1.0
225     225  68wfd.png  68wfd      68wfd     True            1.0
226     226  68x48.png  68x48      68x48     True            1.0
227     227  6b46g.png  6b46g      6b46g     True            1.0
228     228  6b4w6.png  6b4w6      6b4w6     True            1.0
229     229  6bdn5.png  6bdn5      6bdn5     True            1.0
230     230  6bnnm.png  6bnnm      6bnnn    False            0.8
231     231  6bxwg.png  6bxwg      6bxwg     True            1.0
232     232  6c3n6.png  6c3n6      6c3n8    False            0.8
233     233  6c3p5.png  6c3p5      6c3p5     True            1.0
234     234  6cm6m.png  6cm6m      6cm6m     True            1.0
235     235  6cwxe.png  6cwxe      6cwxe     True            1.0
236     236  6dd2y.png  6dd2y      6dd2y     True            1.0
237     237  6dmx7.png  6dmx7      6dmx7     True            1.0
238     238  6e2dg.png  6e2dg      6e2dg     True            1.0
239     239  6e554.png  6e554      6e554     True            1.0
240     240  6e6pn.png  6e6pn      6e6pn     True            1.0
241     241  6ecbn.png  6ecbn      6ecbn     True            1.0
242     242  6end3.png  6end3      6end3     True            1.0
243     243  6f2yc.png  6f2yc      6fcg3    False            0.4
244     244  6f857.png  6f857      6f857     True            1.0
245     245  6fg8c.png  6fg8c      6fg8c     True            1.0
246     246  6fgdw.png  6fgdw      6fgdc    False            0.8
247     247  6fn84.png  6fn84      6fn84     True            1.0
248     248  6g45w.png  6g45w      6g45w     True            1.0
249     249  6ge3p.png  6ge3p      6ne3p    False            0.8
250     250  6gnm3.png  6gnm3      6gnx3    False            0.8
251     251  6m5eg.png  6m5eg      6m5eg     True            1.0
252     252  6mege.png  6mege      6mege     True            1.0
253     253  6mn8n.png  6mn8n      6mn8n     True            1.0
254     254  6mygb.png  6mygb      6mygb     True            1.0
255     255  6n443.png  6n443      6n443     True            1.0
256     256  6n5fd.png  6n5fd      6n5fd     True            1.0
257     257  6n6gg.png  6n6gg      6n6gg     True            1.0
258     258  6ng6n.png  6ng6n      6ng6n     True            1.0
259     259  6ng6w.png  6ng6w      6ng6w     True            1.0
260     260  6p2ge.png  6p2ge      6pfge    False            0.8
261     261  6p7gx.png  6p7gx      6p7gx     True            1.0
262     262  6pfy4.png  6pfy4      6pfy4     True            1.0
263     263  6pwcn.png  6pwcn      6pwcn     True            1.0
264     264  6wb76.png  6wb76      6wb76     True            1.0
265     265  6wg4n.png  6wg4n      6wg4b    False            0.8
266     266  6wnyc.png  6wnyc      6wnyc     True            1.0
267     267  6xen4.png  6xen4      6xen4     True            1.0
268     268  6xpme.png  6xpme      6xpme     True            1.0
269     269  6xxdx.png  6xxdx      6xxnx    False            0.8
270     270  6ydyp.png  6ydyp      64dyp    False            0.8
271     271  728n8.png  728n8      728n8     True            1.0
272     272  72m6f.png  72m6f      72m6f     True            1.0
273     273  73mnx.png  73mnx      73mnx     True            1.0
274     274  74853.png  74853      74853     True            1.0
275     275  74eyg.png  74eyg      74eyg     True            1.0
276     276  75pfw.png  75pfw      75pfw     True            1.0
277     277  7634y.png  7634y      7634y     True            1.0
278     278  76353.png  76353      76353     True            1.0
279     279  76n7p.png  76n7p      76n7p     True            1.0
280     280  76nxn.png  76nxn      76nxn     True            1.0
281     281  76y6f.png  76y6f      76y6f     True            1.0
282     282  77387.png  77387      77387     True            1.0
283     283  77n6g.png  77n6g      77n6g     True            1.0
284     284  77wp4.png  77wp4      77wp4     True            1.0
285     285  785n4.png  785n4      785n4     True            1.0
286     286  78eec.png  78eec      78eec     True            1.0
287     287  7b4bm.png  7b4bm      7b4bm     True            1.0
288     288  7bb7b.png  7bb7b      7bm8b    False            0.6
289     289  7bwm2.png  7bwm2      7bwm2     True            1.0
290     290  7cdge.png  7cdge      7cdge     True            1.0
291     291  7cgym.png  7cgym      7cgym     True            1.0
292     292  7d44m.png  7d44m      7d44m     True            1.0
293     293  7dgc2.png  7dgc2      7dgc2     True            1.0
294     294  7dwx4.png  7dwx4      7dwx4     True            1.0
295     295  7dxbd.png  7dxbd      7dxbd     True            1.0
296     296  7dyww.png  7dyww      7dyww     True            1.0
297     297  7e2y7.png  7e2y7      7e2y7     True            1.0
298     298  7f8b3.png  7f8b3      7f8b3     True            1.0
299     299  7fde7.png  7fde7      7fdn7    False            0.8
300     300  7fmcy.png  7fmcy      7fmcy     True            1.0
301     301  7g3nf.png  7g3nf      7g3nf     True            1.0
302     302  7gce6.png  7gce6      7gce6     True            1.0
303     303  7gmf3.png  7gmf3      7gmf3     True            1.0
304     304  7gnge.png  7gnge      7gnge     True            1.0
305     305  7gp47.png  7gp47      7gp47     True            1.0